image: Visual Studio 2022
version: 1.0.{build}
configuration: Release

init:
- if "%APPVEYOR_REPO_NAME%" == "JeremyAnsel/XwaExePatcher" if "%APPVEYOR_REPO_BRANCH%"=="master" if not defined APPVEYOR_PULL_REQUEST_NUMBER set DEPLOY=True

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'

nuget:
  disable_publish_on_pr: true

build:
  project: XwaExePatcher\XwaExePatcher.sln
  verbosity: minimal

after_build:
- XwaExePatcher\build-dist.cmd

artifacts:
- path: XwaExePatcher\dist\lib
  name: JeremyAnsel.Xwa.ExePatcher-$(APPVEYOR_BUILD_VERSION)
  type: zip
- path: XwaExePatcher\dist\Console
  name: XwaExePatcherConsole-$(APPVEYOR_BUILD_VERSION)
  type: zip
- path: XwaExePatcher\dist\Window
  name: XwaExePatcher-$(APPVEYOR_BUILD_VERSION)
  type: zip
